<head>
<title>Rose City Blues | Music</title>

<?php require_once('m_hat.php'); ?>

<p class="header">Live Music</p><br>
<p class="namescenter">Nathan James</p> 
<p class="basepaddedcenter"><a href="http://www.nathandjames.com/" target="new">www.nathandjames.com</a></p> 
<img src="biopictures/mus_nathandjames.jpg" alt="" width="400" height="600" class="bodypic"/>
<p class="basepaddedcenter">photo by Jon Naugle</p>
<p class="basepadded">Never one to follow convention, and always one to think for himself, Nathan James has created a musical identity with his homemade instruments and self taught skills. Whether you catch Nathan James as his true one man band pickin' and scratchin' on his own invention of washboard guitar, stomping out time on his custom suitcase drum set while singing and blowing harmonica or kazoo; or leading his new trio, you are sure to be moved and impressed with the unique energy and soul that he possesses. Nathan James is a well respected and experienced artist in his field. For 15 years now, he has successfully made his living touring and recording, solely specializing on his passion of blues, and American roots music. Starting his career of full time gigging musician at age 18, Nathan is no stranger to live performance.</p>

<p class="basepadded">Drawing from a deep well of influences from many early roots artists and styles, James was quickly attracted to the individuality of self made music and artistic expression. While simultaneously discovering the guitar and the blues at age 13, Nathan James has since been in complete focus as to where his life goal would lead. Growing up in the small town of Fallbrook Ca, has been influential in deciding to choose this path. "There wasn't a lot to do here, so you either got in trouble, or found something productive to do!" Having supportive parents that didn't force him into the usual college after high school allowed Nathan to go straight into the 'real working world' of playing music. "Part of it was luck that I was able to get paying gigs right off the bat!" Local San Diego blues bands the Blues Pharaohs and Billy Watson gave Nathan a chance to get his feet wet with enough local gigs to support himself literally a month after graduating high school! This led to also working with well known Southern California blues acts Jamie Wood, and Johnny Dyer. At age 19 Nathan got the call from internationally known blues veteran James Harman to join his band and tour the country. With Harman is where he gained the experience that has shaped most of his own career.</p>

<p class="basepadded">After touring and recording nonstop with Harman for 3 1/2 years, Nathan decided to have a go at literally a solo career- that is playing one man acoustic based blues. This was instantly successful, leading to playing over 30 gigs a month at times!! With the strain of carrying the entire show by yourself all the time, Nathan met up with harmonica player/vocalist Ben Hernandez, a like minded young blues roots musician aficionado, and together they started working as a duo. As word spread of these two and their ability to bring back to life the spirit of duos like Sonny Terry and Brownie Mcghee country blues, they gained international notoriety while traveling all over the West Coast and; In 2007, they entered the International Blues Challenge in Memphis TN, and took 1st place! This really has made their reputation spread like wildfire. That year alone the duo traveled to Denmark, Italy and Taiwan. During his career Nathan has worked with other many well known artists including: Kim Wilson, Pinetop Perkins, Billy Boy Arnold, Lazy Lester, Johnny Dyer, Janiva Magness, Rick Holmstrom, Mark Hummel and Gary Primich. </p>

<p class="basepadded">Currently Nathan’s three piece band is forging a cumulative sound that combines elements of 1920's acoustic blues, amplified juke joint hill country, and 1950's uptown blues mixed with 1960's soulful R&B! Influences range from Tampa Red, to B.B. King, to James Brown and the Famous Flames. This is not your average blues power trio that leans towards the much abused "blues rock" formula. Instead each member in the band knows all the nuances of the different feels and tones. Knowing how to get people's attention, Nathan will often go out solo from the bandstand and burst into a frenzied ragtime breakdown that can lead to a washboard solo on his custom LED lit 'Washtar Gitboard'! Another unique aspect of a live show is band mate Troy Sandow. He may start off the set on upright bass while Nathan will play an uptown lead guitar style in the vein of B.B. or T-bone Walker. Then he will switch over to amplified harmonica and Nathan will fingerpick a driving groove on his baritone guitar in the style of R.L. Burnside or Lightnin' Hopkins. Although Nathan's band pays homage to these traditions and has the same quality of musicianship, there is an original and fresh new energy coming from musicians of a much younger generation.</p>
<br>
<br>
<p class="namescenter">The Fried Bananas</p> 
<p class="basepaddedcenter"><a href="http://www.thefriedbananas.com" target="new">www.thefriedbananas.com</a></p> 
<img src="biopictures/mus_fb.jpg" alt="" width="450" height="300" class="bodypic"/>
<p class="basepadded">Louis Armstrong said it best, “The main thing is to live for that audience, ’cause what you’re there for is to please the people.” This is the core belief of this highly acclaimed band, and dancers from events like bluesSHOUT!, Montreal Dance Fest, Nocturne Blues, Mile High Blues, and more are singing (and dancing) their praise:</p>
<p class="basepadded"><em>“You wouldn’t believe the amazing feedback we’re getting. I don’t think I’ve ever had such a great response to a band.”</em> -Heidi Fite, bluesSHOUT! founder</p>
<p class="basepadded"><em>“First off, they rock. Secondly, the name is no joke: they really lay the heat down and make your nether regions want to jump around.”</em> -Davis Thurber, Montreal Dance Fest founder, teacher and performer</p>
<p class="basepadded">The Fried Bananas was first assembled in 2006 under the guidance of co-leaders Shawn Hershey and Josh Fialkoff, who are both dancers themselves. Together they carefully crafted the Bananas’ sound, drawing inspiration from jazz greats like Louis Armstrong, Sidney Bechet, and Dr. Michael White. Since then, this versatile band has evolved to incorporate other blues influences from New Orleans to the Delta, from Chicago to New York City, from the 1900s to today. So if you’re looking for Ballroomin’ or Jookin’, or perhaps something a tad on the funky side, The Fried Bananas has your back, and your dancing shoes.</p>

<br>
<br>
<p class="namescenter">Kevin Selfe and The Tornadoes</p>
<p class="basepaddedcenter"><a href="http://kevinselfe.com" target="new">http://kevinselfe.com</a></p> 
<img src="biopictures/mus_kevin.jpg" alt="" width="400" height="600" class="bodypic"/>
<p class="basepadded">Kevin Selfe has been electrifying audiences nationwide since breaking into the blues scene in 2006. His growing stature as a captivating story teller and passionate performer are surpassed only by his deft mastery of blues guitar. Having relocated to Portland, OR, the Virginia native is now a leading light in the Pacific Northwest’s robust blues revival. Effortlessly combining the guitar traditions of the legends and the modern masters into his own unique approach, Selfe’s stylistic depth and electric performances resonate with audiences. His live shows have grown in legend largely due to his unique gift for communicating, through guitar, the complex range of moods revealed only by blues. Selfe’s songwriting style bridges the gap between joy and angst, using piercing irony, humorous metaphors, and daring autobiographical subject matter from his own occasional walks with the blues.</p>

<p class="basepadded">In six short years Kevin Selfe and The Tornadoes have become a fan favorite in the Northwest and beyond. In August 2013, Kevin was nominated for a Blues Blast Award, and the band was inducted into the Cascade Blues Association Hall of Fame in late 2012 . They’ve won 15 prestigious Muddy Awards from the CBA for Traditional Blues Act of The Year (2013, 2012, 2011, 2010), Contemporary Blues Act of The Year (2013, 2009), Performance of the Year (2013, 2012), Electric Guitar (2013, 2012), Drums (2013, 2012, 2011), NW Recording of The Year (2013), and National Recording of The Year (2013). They are the only act in the 25 year history of the awards to win for both Traditional and Contemporary Blues Act of the Year demonstrating their musical diversity and depth.</p>

<p class="namescenter">More to come!</p>

<p class="header">DJs</p>

<p class="basepaddedcenter">TBA</p>

<?php require_once('m_shoes.php'); ?>